// app/layout.tsx
import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "./Components/NavbarWrapper";
import '@fontsource/kanit';

const kanit = Kanit({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Your Company Name",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={`${kanit} bg-gradient-to-br from-blue-500 to-indigo-600 text-black antialiased`}>
        <NavbarWrapper />
        {children}
      </body>
    </html>
  );
}
